-- SUPERSEDED — never applied to any environment. Intentionally inert (no DDL).
--
-- This migration proposed an assignee-only hardening of docs/tasks/activity/
-- attachment reads (functions is_admin_for_rls / can_read_doc_for_rls /
-- can_read_task_for_rls / can_read_task_comment_for_rls / can_read_task_path_for_rls
-- plus rewritten policies). It was NEVER applied: verified 2026-07-10 against the
-- live database — none of those functions exist and no policy references them.
--
-- The tasks hardening it intended was instead delivered with a DIFFERENT, verified
-- rule (staff = admin OR non-investor, not assignee-only):
--   • 20260710193947_tasks_staff_rls        — staff-scope tasks + task_comments reads/writes (APPLIED live 2026-07-10)
--   • 20260710200000_tasks_api_only_writes   — drop staff task writes → API-only (DEPLOY-STAGED)
--
-- The body was emptied so a stray `supabase db push` (or a hand-run of this file)
-- cannot cold-apply the abandoned assignee-only rule over the live staff policies.
-- Docs/activity/attachment hardening remains an open follow-up tracked separately;
-- do NOT resurrect this file for it — write a fresh, verified migration instead.
--
-- (intentionally empty)
